version: '3.8'

services:
  backend:
    build:
      context: ./backend_node
      dockerfile: Dockerfile
    container_name: project-manager-backend
    ports:
      - "8010:8010"
    environment:
      - APP_PORT=8010
      - APP_HOST=0.0.0.0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    env_file:
      - ./backend_node/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8010}
    container_name: project-manager-frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3005"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

