services:
  backend:
    build:
      context: ./backend
    container_name: project_manager_backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=8010
    ports:
      - "8010:8010"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8010/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: project_manager_frontend
    depends_on:
      - backend
    ports:
      - "3005:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

