version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: crm_node_backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ALGORITHM=${ALGORITHM:-HS256}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://3.85.144.221:3003}
      - PORT=8008
    ports:
      - "8008:8008"
    restart: unless-stopped


